import { createSlice } from "@reduxjs/toolkit";
const employeesDatatest = [
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "zyman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "cyman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "eeee",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "fffff",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "fkkkk",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
  {
    city: "Albuquerque",
    dateOfBirth: "2022-05-04",
    department: "MARKETING",
    firstName: "Ayman",
    lastName: "Moussa",
    startDate: "2022-05-07",
    state: "AMERICAN SAMOA",
    street: "2105 Vista Oeste St NW Suite E - 1146",
    zipCode: "87120",
  },
];
export const employeesSlice = createSlice({
  name: "employees",
  initialState: {
    modal: true,
    employeesData: employeesDatatest,
  },
  reducers: {
    openModal: (state) => {
      state.modal = !state.modal;
    },
    addEmployee: (state, action) => {
      state.employeesData.unshift(action.payload);
    },
  },
});
export const { openModal, addEmployee } = employeesSlice.actions;

export default employeesSlice.reducer;
